In [1]:
import numpy as np

# The Basics

In [13]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [14]:
b = np.array([[1,2,3,4],[2,3,4,3]])
b

array([[1, 2, 3, 4],
       [2, 3, 4, 3]])

In [21]:
# Get Dimension
b.ndim

2

In [22]:
#Get Shape
a.shape

(4,)

In [23]:
b.shape

(2, 4)

In [24]:
#get Type
a.dtype

dtype('int32')

In [25]:
b.dtype

dtype('int32')

In [26]:
#get size
a.itemsize

4

In [27]:
b.itemsize

4

In [28]:
#Get total size
a.nbytes

16

In [29]:
b.nbytes

32

# accessing/changing specific elements, rows, columns

In [30]:
a = np.array([[1,2,3,4,5,6,8,9],[23,34,5,78,98,12,2,34]])
a

array([[ 1,  2,  3,  4,  5,  6,  8,  9],
       [23, 34,  5, 78, 98, 12,  2, 34]])

In [31]:
a.shape

(2, 8)

In [32]:
# Get a specific element [r, c]
a[1, 5]

12

In [33]:
a[0,6]

8

In [34]:
#Get specific row
a[1, :]

array([23, 34,  5, 78, 98, 12,  2, 34])

In [36]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 8, 9])

In [37]:
# GEt specific column
a[:, 1]

array([ 2, 34])

In [38]:
a[:, 0]

array([ 1, 23])

In [39]:
a[:, 7]

array([ 9, 34])

In [42]:
#Geting a little more fancy (startindex:endindex:stepsize)
a[0, 1:6:2]


array([2, 4, 6])

In [44]:
a[1, 1:-1:2]

array([34, 78, 12])

In [47]:
a[1,4] = 39
a

array([[ 1,  2,  3,  4,  5,  6,  8,  9],
       [23, 34,  5, 78, 39, 12,  2, 34]])

In [51]:
a[0,3]
a


array([[ 1,  2,  3, 56,  5,  6,  8,  9],
       [23, 34,  5, 78, 39, 12,  2, 34]])

In [52]:
a[0,3] = 567
a

array([[  1,   2,   3, 567,   5,   6,   8,   9],
       [ 23,  34,   5,  78,  39,  12,   2,  34]])